### ISSUE TITLE
[🐛] Discrepancy in Purchase Event Tracking Between Firebase and AppsFlyer

### ISSUE THREAD

**Issue by ms4ever7** [invertase/react-native-firebase#7693]
## Issue

We're encountering a significant gap between session counts and purchase event tracking in Firebase Analytics compared to AppsFlyer. Despite verifying that our implementation is correct and testing data transmission using debug views in Firebase, we're still experiencing discrepancies in user data.

Details:

Problem: We're observing a discrepancy between session counts and purchase event tracking in Firebase Analytics compared to AppsFlyer. The gap between sessions reported in Firebase (GA4 => BigQuery) and AppsFlyer is substantial.

Context: Our app is built using React Native, and we're utilizing react-native-firebase version 14.11.0 for Firebase Analytics integration.

Observations:
Verified correct implementation: We've thoroughly checked our implementation and confirmed that purchase events are being correctly tracked and sent to Firebase Analytics. (Done it through DebugView in both Firebase and GA4)
Debug view testing: Testing using debug views in Firebase shows that purchase events are being properly sent from our React Native app.
No evident issues: We haven't identified any evident issues with network connectivity, user consent, or ad blockers that could explain the discrepancies.
Attempted Solutions:
Reviewed release notes: We've reviewed the release notes for react-native-firebase version 19.0.1, but upgrading to the latest version should not be the case (we are currently having 14.11.0)
Consulted documentation: We've checked the Firebase Analytics documentation and react-native-firebase documentation for any relevant updates or best practices.
Request: We're seeking assistance in identifying the root cause of the discrepancy between Firebase Analytics and AppsFlyer regarding session counts and purchase event tracking. Any insights, suggestions, or troubleshooting steps would be greatly appreciated.

React Native version: 0.68.2
react-native-firebase version: 14.11.0

```import analytics, { FirebaseAnalyticsTypes } from '@react-native-firebase/analytics';
import appTransparency, { AppTransparencyService } from '../AppTransparency/service';
import { OneTrustCategory, OneTrustConsentStatus } from '../OneTrust/consts';
import oneTrust, { OneTrustService } from '../OneTrust/service';

export class FirebaseAnalyticsService {
    public constructor(private analyticsModule: FirebaseAnalyticsTypes.Module,
                       private oneTrustService: OneTrustService,
                       private appTransparencyService: AppTransparencyService) {
    }

    public init = () => this.checkConsentStatus();

    public logEvent = (eventName: string, params?: { [key: string]: any }): Promise<void> => this.analyticsModule.logEvent(eventName, params);

    public setUserId = (id: string | null): Promise<void> => this.analyticsModule.setUserId(id);

    private checkConsentStatus = async () => {
        const consentStatus = await this.oneTrustService.getConsentStatus(OneTrustCategory.ANALYTICS);
        const isAllowed = await this.appTransparencyService.isAllowed();

        await this.analyticsModule.setAnalyticsCollectionEnabled(consentStatus !== OneTrustConsentStatus.NOT_GIVEN && isAllowed);

        this.oneTrustService.getConsentStatusChangeObservable(OneTrustCategory.ANALYTICS).subscribe((status: OneTrustConsentStatus) => {
            this.analyticsModule.setAnalyticsCollectionEnabled(status !== OneTrustConsentStatus.NOT_GIVEN && isAllowed);
        });
    };
}

export default new FirebaseAnalyticsService(analytics(), oneTrust, appTransparency);
```

Unfortunately problem exists only for purchase event, for all other events everything is fine, here is an example of how we send the firebase and appsflyer events:
```
      const ecommercePurchasePayload = {
            transaction_id: `${checkoutAnalyticsData!.orderId}`,
            coupon: checkoutAnalyticsData!.discountCode != null ? checkoutAnalyticsData!.discountCode : null,
            currency: checkoutSummary.total!.currency,
            value: +checkoutSummary.total!.amount,
            shipping: +checkoutSummary.deliveryCharge.amount,
            items: formattedBasketItems,
            new_customer: !!getAccountPreviousOrderCount(store$.value),
        };

        analyticsService.logEvent('purchase', ecommercePurchasePayload); // FIREBASE service sent aboe

        appsFlyerService.logEvent(getAccountPreviousOrderCount(store$.value) ? AppsFlyerEvent.PURCHASE : AppsFlyerEvent.FIRST_PURCHASE, afObjectData); //afObjectData is also sent in the code but its not needed here
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^14.11.0",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/crashlytics": "^14.11.0",
    "@react-native-firebase/messaging": "^14.11.0",
    "@react-native-firebase/remote-config": "^14.11.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - Y

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
My first take is that this is out of support and represents an enormous amount of deferred maintenance that is due immediately in order to comply with Apple Privacy Manifest requirements that came in force this month:

> react-native-firebase version 14.11.0
